
package cz.it4i.hpcaas.filetransfer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileTransferWsSoap", targetNamespace = "http://hpcaas.it4i.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileTransferWsSoap {


    /**
     * 
     * @param submittedJobInfoId
     * @param sessionCode
     * @return
     *     returns cz.it4i.hpcaas.filetransfer.FileTransferMethodExt
     */
    @WebMethod(operationName = "GetFileTransferMethod", action = "http://hpcaas.it4i.cz/GetFileTransferMethod")
    @WebResult(name = "GetFileTransferMethodResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "GetFileTransferMethod", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.GetFileTransferMethod")
    @ResponseWrapper(localName = "GetFileTransferMethodResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.GetFileTransferMethodResponse")
    public FileTransferMethodExt getFileTransferMethod(
        @WebParam(name = "submittedJobInfoId", targetNamespace = "http://hpcaas.it4i.cz/")
        long submittedJobInfoId,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

    /**
     * 
     * @param submittedJobInfoId
     * @param sessionCode
     * @param usedTransferMethod
     */
    @WebMethod(operationName = "EndFileTransfer", action = "http://hpcaas.it4i.cz/EndFileTransfer")
    @RequestWrapper(localName = "EndFileTransfer", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.EndFileTransfer")
    @ResponseWrapper(localName = "EndFileTransferResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.EndFileTransferResponse")
    public void endFileTransfer(
        @WebParam(name = "submittedJobInfoId", targetNamespace = "http://hpcaas.it4i.cz/")
        long submittedJobInfoId,
        @WebParam(name = "usedTransferMethod", targetNamespace = "http://hpcaas.it4i.cz/")
        FileTransferMethodExt usedTransferMethod,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

    /**
     * 
     * @param submittedJobInfoId
     * @param taskFileOffsets
     * @param sessionCode
     * @return
     *     returns cz.it4i.hpcaas.filetransfer.ArrayOfJobFileContentExt
     */
    @WebMethod(operationName = "DownloadPartsOfJobFilesFromCluster", action = "http://hpcaas.it4i.cz/DownloadPartsOfJobFilesFromCluster")
    @WebResult(name = "DownloadPartsOfJobFilesFromClusterResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "DownloadPartsOfJobFilesFromCluster", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.DownloadPartsOfJobFilesFromCluster")
    @ResponseWrapper(localName = "DownloadPartsOfJobFilesFromClusterResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.DownloadPartsOfJobFilesFromClusterResponse")
    public ArrayOfJobFileContentExt downloadPartsOfJobFilesFromCluster(
        @WebParam(name = "submittedJobInfoId", targetNamespace = "http://hpcaas.it4i.cz/")
        long submittedJobInfoId,
        @WebParam(name = "taskFileOffsets", targetNamespace = "http://hpcaas.it4i.cz/")
        ArrayOfTaskFileOffsetExt taskFileOffsets,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

    /**
     * 
     * @param submittedJobInfoId
     * @param sessionCode
     * @return
     *     returns cz.it4i.hpcaas.filetransfer.ArrayOfString
     */
    @WebMethod(operationName = "ListChangedFilesForJob", action = "http://hpcaas.it4i.cz/ListChangedFilesForJob")
    @WebResult(name = "ListChangedFilesForJobResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "ListChangedFilesForJob", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.ListChangedFilesForJob")
    @ResponseWrapper(localName = "ListChangedFilesForJobResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.ListChangedFilesForJobResponse")
    public ArrayOfString listChangedFilesForJob(
        @WebParam(name = "submittedJobInfoId", targetNamespace = "http://hpcaas.it4i.cz/")
        long submittedJobInfoId,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

    /**
     * 
     * @param submittedJobInfoId
     * @param sessionCode
     * @param relativeFilePath
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "DownloadFileFromCluster", action = "http://hpcaas.it4i.cz/DownloadFileFromCluster")
    @WebResult(name = "DownloadFileFromClusterResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "DownloadFileFromCluster", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.DownloadFileFromCluster")
    @ResponseWrapper(localName = "DownloadFileFromClusterResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.filetransfer.DownloadFileFromClusterResponse")
    public byte[] downloadFileFromCluster(
        @WebParam(name = "submittedJobInfoId", targetNamespace = "http://hpcaas.it4i.cz/")
        long submittedJobInfoId,
        @WebParam(name = "relativeFilePath", targetNamespace = "http://hpcaas.it4i.cz/")
        String relativeFilePath,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

}
