
package cz.it4i.hpcaas.jobmgmt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JobManagementWs", targetNamespace = "http://hpcaas.it4i.cz/", wsdlLocation = "https://haas.it4i.cz/HaasWsExcape/JobManagementWs.asmx?WSDL")
public class JobManagementWs
    extends Service
{

    private final static URL JOBMANAGEMENTWS_WSDL_LOCATION;
    private final static WebServiceException JOBMANAGEMENTWS_EXCEPTION;
    private final static QName JOBMANAGEMENTWS_QNAME = new QName("http://hpcaas.it4i.cz/", "JobManagementWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://haas.it4i.cz/HaasWsExcape/JobManagementWs.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOBMANAGEMENTWS_WSDL_LOCATION = url;
        JOBMANAGEMENTWS_EXCEPTION = e;
    }

    public JobManagementWs() {
        super(__getWsdlLocation(), JOBMANAGEMENTWS_QNAME);
    }

    public JobManagementWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOBMANAGEMENTWS_QNAME, features);
    }

    public JobManagementWs(URL wsdlLocation) {
        super(wsdlLocation, JOBMANAGEMENTWS_QNAME);
    }

    public JobManagementWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOBMANAGEMENTWS_QNAME, features);
    }

    public JobManagementWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobManagementWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JobManagementWsSoap
     */
    @WebEndpoint(name = "JobManagementWsSoap")
    public JobManagementWsSoap getJobManagementWsSoap() {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "JobManagementWsSoap"), JobManagementWsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobManagementWsSoap
     */
    @WebEndpoint(name = "JobManagementWsSoap")
    public JobManagementWsSoap getJobManagementWsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "JobManagementWsSoap"), JobManagementWsSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns JobManagementWsSoap
     */
    @WebEndpoint(name = "JobManagementWsSoap12")
    public JobManagementWsSoap getJobManagementWsSoap12() {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "JobManagementWsSoap12"), JobManagementWsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobManagementWsSoap
     */
    @WebEndpoint(name = "JobManagementWsSoap12")
    public JobManagementWsSoap getJobManagementWsSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "JobManagementWsSoap12"), JobManagementWsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOBMANAGEMENTWS_EXCEPTION!= null) {
            throw JOBMANAGEMENTWS_EXCEPTION;
        }
        return JOBMANAGEMENTWS_WSDL_LOCATION;
    }

}
