
package cz.it4i.hpcaas.usermgmgmt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserAndLimitationManagementWsSoap", targetNamespace = "http://hpcaas.it4i.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserAndLimitationManagementWsSoap {


    /**
     * 
     * @param credentials
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AuthenticateUserPassword", action = "http://hpcaas.it4i.cz/AuthenticateUserPassword")
    @WebResult(name = "AuthenticateUserPasswordResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "AuthenticateUserPassword", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.usermgmgmt.AuthenticateUserPassword")
    @ResponseWrapper(localName = "AuthenticateUserPasswordResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.usermgmgmt.AuthenticateUserPasswordResponse")
    public String authenticateUserPassword(
        @WebParam(name = "credentials", targetNamespace = "http://hpcaas.it4i.cz/")
        PasswordCredentialsExt credentials);

    /**
     * 
     * @param credentials
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AuthenticateUserDigitalSignature", action = "http://hpcaas.it4i.cz/AuthenticateUserDigitalSignature")
    @WebResult(name = "AuthenticateUserDigitalSignatureResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "AuthenticateUserDigitalSignature", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.usermgmgmt.AuthenticateUserDigitalSignature")
    @ResponseWrapper(localName = "AuthenticateUserDigitalSignatureResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.usermgmgmt.AuthenticateUserDigitalSignatureResponse")
    public String authenticateUserDigitalSignature(
        @WebParam(name = "credentials", targetNamespace = "http://hpcaas.it4i.cz/")
        DigitalSignatureCredentialsExt credentials);

    /**
     * 
     * @param sessionCode
     * @return
     *     returns cz.it4i.hpcaas.usermgmgmt.ArrayOfResourceUsageExt
     */
    @WebMethod(operationName = "GetCurrentUsageAndLimitationsForCurrentUser", action = "http://hpcaas.it4i.cz/GetCurrentUsageAndLimitationsForCurrentUser")
    @WebResult(name = "GetCurrentUsageAndLimitationsForCurrentUserResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "GetCurrentUsageAndLimitationsForCurrentUser", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.usermgmgmt.GetCurrentUsageAndLimitationsForCurrentUser")
    @ResponseWrapper(localName = "GetCurrentUsageAndLimitationsForCurrentUserResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.usermgmgmt.GetCurrentUsageAndLimitationsForCurrentUserResponse")
    public ArrayOfResourceUsageExt getCurrentUsageAndLimitationsForCurrentUser(
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

}
