
package cz.it4i.hpcaas.usermgmgmt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserAndLimitationManagementWs", targetNamespace = "http://hpcaas.it4i.cz/", wsdlLocation = "https://haas.it4i.cz/HaasWsExcape/UserAndLimitationManagementWs.asmx?WSDL")
public class UserAndLimitationManagementWs
    extends Service
{

    private final static URL USERANDLIMITATIONMANAGEMENTWS_WSDL_LOCATION;
    private final static WebServiceException USERANDLIMITATIONMANAGEMENTWS_EXCEPTION;
    private final static QName USERANDLIMITATIONMANAGEMENTWS_QNAME = new QName("http://hpcaas.it4i.cz/", "UserAndLimitationManagementWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://haas.it4i.cz/HaasWsExcape/UserAndLimitationManagementWs.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERANDLIMITATIONMANAGEMENTWS_WSDL_LOCATION = url;
        USERANDLIMITATIONMANAGEMENTWS_EXCEPTION = e;
    }

    public UserAndLimitationManagementWs() {
        super(__getWsdlLocation(), USERANDLIMITATIONMANAGEMENTWS_QNAME);
    }

    public UserAndLimitationManagementWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERANDLIMITATIONMANAGEMENTWS_QNAME, features);
    }

    public UserAndLimitationManagementWs(URL wsdlLocation) {
        super(wsdlLocation, USERANDLIMITATIONMANAGEMENTWS_QNAME);
    }

    public UserAndLimitationManagementWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERANDLIMITATIONMANAGEMENTWS_QNAME, features);
    }

    public UserAndLimitationManagementWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserAndLimitationManagementWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserAndLimitationManagementWsSoap
     */
    @WebEndpoint(name = "UserAndLimitationManagementWsSoap")
    public UserAndLimitationManagementWsSoap getUserAndLimitationManagementWsSoap() {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "UserAndLimitationManagementWsSoap"), UserAndLimitationManagementWsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserAndLimitationManagementWsSoap
     */
    @WebEndpoint(name = "UserAndLimitationManagementWsSoap")
    public UserAndLimitationManagementWsSoap getUserAndLimitationManagementWsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "UserAndLimitationManagementWsSoap"), UserAndLimitationManagementWsSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns UserAndLimitationManagementWsSoap
     */
    @WebEndpoint(name = "UserAndLimitationManagementWsSoap12")
    public UserAndLimitationManagementWsSoap getUserAndLimitationManagementWsSoap12() {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "UserAndLimitationManagementWsSoap12"), UserAndLimitationManagementWsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserAndLimitationManagementWsSoap
     */
    @WebEndpoint(name = "UserAndLimitationManagementWsSoap12")
    public UserAndLimitationManagementWsSoap getUserAndLimitationManagementWsSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "UserAndLimitationManagementWsSoap12"), UserAndLimitationManagementWsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERANDLIMITATIONMANAGEMENTWS_EXCEPTION!= null) {
            throw USERANDLIMITATIONMANAGEMENTWS_EXCEPTION;
        }
        return USERANDLIMITATIONMANAGEMENTWS_WSDL_LOCATION;
    }

}
