
package cz.it4i.hpcaas.jobreporting;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JobReportingWs", targetNamespace = "http://hpcaas.it4i.cz/", wsdlLocation = "https://haas.it4i.cz/HaasWsExcape/JobReportingWs.asmx?WSDL")
public class JobReportingWs
    extends Service
{

    private final static URL JOBREPORTINGWS_WSDL_LOCATION;
    private final static WebServiceException JOBREPORTINGWS_EXCEPTION;
    private final static QName JOBREPORTINGWS_QNAME = new QName("http://hpcaas.it4i.cz/", "JobReportingWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://haas.it4i.cz/HaasWsExcape/JobReportingWs.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOBREPORTINGWS_WSDL_LOCATION = url;
        JOBREPORTINGWS_EXCEPTION = e;
    }

    public JobReportingWs() {
        super(__getWsdlLocation(), JOBREPORTINGWS_QNAME);
    }

    public JobReportingWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOBREPORTINGWS_QNAME, features);
    }

    public JobReportingWs(URL wsdlLocation) {
        super(wsdlLocation, JOBREPORTINGWS_QNAME);
    }

    public JobReportingWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOBREPORTINGWS_QNAME, features);
    }

    public JobReportingWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobReportingWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JobReportingWsSoap
     */
    @WebEndpoint(name = "JobReportingWsSoap")
    public JobReportingWsSoap getJobReportingWsSoap() {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "JobReportingWsSoap"), JobReportingWsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobReportingWsSoap
     */
    @WebEndpoint(name = "JobReportingWsSoap")
    public JobReportingWsSoap getJobReportingWsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "JobReportingWsSoap"), JobReportingWsSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns JobReportingWsSoap
     */
    @WebEndpoint(name = "JobReportingWsSoap12")
    public JobReportingWsSoap getJobReportingWsSoap12() {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "JobReportingWsSoap12"), JobReportingWsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobReportingWsSoap
     */
    @WebEndpoint(name = "JobReportingWsSoap12")
    public JobReportingWsSoap getJobReportingWsSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://hpcaas.it4i.cz/", "JobReportingWsSoap12"), JobReportingWsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOBREPORTINGWS_EXCEPTION!= null) {
            throw JOBREPORTINGWS_EXCEPTION;
        }
        return JOBREPORTINGWS_WSDL_LOCATION;
    }

}
