
package cz.it4i.hpcaas.jobreporting;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JobReportingWsSoap", targetNamespace = "http://hpcaas.it4i.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JobReportingWsSoap {


    /**
     * 
     * @param sessionCode
     * @return
     *     returns cz.it4i.hpcaas.jobreporting.ArrayOfAdaptorUserGroupExt
     */
    @WebMethod(operationName = "ListAdaptorUserGroups", action = "http://hpcaas.it4i.cz/ListAdaptorUserGroups")
    @WebResult(name = "ListAdaptorUserGroupsResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "ListAdaptorUserGroups", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.jobreporting.ListAdaptorUserGroups")
    @ResponseWrapper(localName = "ListAdaptorUserGroupsResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.jobreporting.ListAdaptorUserGroupsResponse")
    public ArrayOfAdaptorUserGroupExt listAdaptorUserGroups(
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

    /**
     * 
     * @param jobId
     * @param sessionCode
     * @return
     *     returns cz.it4i.hpcaas.jobreporting.SubmittedJobInfoUsageReportExt
     */
    @WebMethod(operationName = "GetResourceUsageReportForJob", action = "http://hpcaas.it4i.cz/GetResourceUsageReportForJob")
    @WebResult(name = "GetResourceUsageReportForJobResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "GetResourceUsageReportForJob", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.jobreporting.GetResourceUsageReportForJob")
    @ResponseWrapper(localName = "GetResourceUsageReportForJobResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.jobreporting.GetResourceUsageReportForJobResponse")
    public SubmittedJobInfoUsageReportExt getResourceUsageReportForJob(
        @WebParam(name = "jobId", targetNamespace = "http://hpcaas.it4i.cz/")
        long jobId,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

    /**
     * 
     * @param sessionCode
     * @param startTime
     * @param endTime
     * @param userId
     * @return
     *     returns cz.it4i.hpcaas.jobreporting.UserResourceUsageReportExt
     */
    @WebMethod(operationName = "GetUserResourceUsageReport", action = "http://hpcaas.it4i.cz/GetUserResourceUsageReport")
    @WebResult(name = "GetUserResourceUsageReportResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "GetUserResourceUsageReport", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.jobreporting.GetUserResourceUsageReport")
    @ResponseWrapper(localName = "GetUserResourceUsageReportResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.jobreporting.GetUserResourceUsageReportResponse")
    public UserResourceUsageReportExt getUserResourceUsageReport(
        @WebParam(name = "userId", targetNamespace = "http://hpcaas.it4i.cz/")
        long userId,
        @WebParam(name = "startTime", targetNamespace = "http://hpcaas.it4i.cz/")
        XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "http://hpcaas.it4i.cz/")
        XMLGregorianCalendar endTime,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

    /**
     * 
     * @param sessionCode
     * @param groupId
     * @param startTime
     * @param endTime
     * @return
     *     returns cz.it4i.hpcaas.jobreporting.UserGroupResourceUsageReportExt
     */
    @WebMethod(operationName = "GetUserGroupResourceUsageReport", action = "http://hpcaas.it4i.cz/GetUserGroupResourceUsageReport")
    @WebResult(name = "GetUserGroupResourceUsageReportResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "GetUserGroupResourceUsageReport", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.jobreporting.GetUserGroupResourceUsageReport")
    @ResponseWrapper(localName = "GetUserGroupResourceUsageReportResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.jobreporting.GetUserGroupResourceUsageReportResponse")
    public UserGroupResourceUsageReportExt getUserGroupResourceUsageReport(
        @WebParam(name = "groupId", targetNamespace = "http://hpcaas.it4i.cz/")
        long groupId,
        @WebParam(name = "startTime", targetNamespace = "http://hpcaas.it4i.cz/")
        XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "http://hpcaas.it4i.cz/")
        XMLGregorianCalendar endTime,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

}
