
package cz.it4i.hpcaas.clusterinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClusterInformationWsSoap", targetNamespace = "http://hpcaas.it4i.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClusterInformationWsSoap {


    /**
     * 
     * @return
     *     returns cz.it4i.hpcaas.clusterinfo.ArrayOfClusterInfoExt
     */
    @WebMethod(operationName = "ListAvailableClusters", action = "http://hpcaas.it4i.cz/ListAvailableClusters")
    @WebResult(name = "ListAvailableClustersResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "ListAvailableClusters", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.clusterinfo.ListAvailableClusters")
    @ResponseWrapper(localName = "ListAvailableClustersResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.clusterinfo.ListAvailableClustersResponse")
    public ArrayOfClusterInfoExt listAvailableClusters();

    /**
     * 
     * @param clusterNodeId
     * @param sessionCode
     * @return
     *     returns cz.it4i.hpcaas.clusterinfo.ClusterNodeUsageExt
     */
    @WebMethod(operationName = "GetCurrentClusterNodeUsage", action = "http://hpcaas.it4i.cz/GetCurrentClusterNodeUsage")
    @WebResult(name = "GetCurrentClusterNodeUsageResult", targetNamespace = "http://hpcaas.it4i.cz/")
    @RequestWrapper(localName = "GetCurrentClusterNodeUsage", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.clusterinfo.GetCurrentClusterNodeUsage")
    @ResponseWrapper(localName = "GetCurrentClusterNodeUsageResponse", targetNamespace = "http://hpcaas.it4i.cz/", className = "cz.it4i.hpcaas.clusterinfo.GetCurrentClusterNodeUsageResponse")
    public ClusterNodeUsageExt getCurrentClusterNodeUsage(
        @WebParam(name = "clusterNodeId", targetNamespace = "http://hpcaas.it4i.cz/")
        long clusterNodeId,
        @WebParam(name = "sessionCode", targetNamespace = "http://hpcaas.it4i.cz/")
        String sessionCode);

}
